### ISSUE TITLE
calls `set_current_dir` in a proc macro?

### ISSUE THREAD

**Issue by cgwalters** [mgattozzi/assay#1]
I've been working on some related code today (see e.g. https://github.com/ostreedev/ostree-rs-ext/pull/244 which is changing our test code there to use more [cap-std](https://docs.rs/cap-std/latest/cap_std/) bits and also trying to more carefully move the processes we fork off into per-test tempdirs).

And just glancing at your code, at least [this call to set_current_dir()](https://github.com/mgattozzi/assay/blob/82500abecc8a6b82bf6e5d313657420a0c18faa8/src/lib.rs#L45) looks suspicious to me, because it looks like we're changing process global state in a *proc macro*.

**Comment by mgattozzi** [comment]
Yeah! More than happy too. Mutating global state willy nilly with a dep has given me my own fair share of multi-week long bugs to debug that aren't fun. Thanks for asking!
