### ISSUE TITLE
Macro does not respect `#[ignore]` attribute

### ISSUE THREAD

**Issue by korrat** [mgattozzi/assay#12]
With the following code, I get an error when running tests with `cargo test`:

```rust
#[assay]
#[ignore]
fn fail() {
    panic!();
}
```

The output is:

```shell
$ cargo test
[...]
running 1 test
test fail ... FAILED
```

I expected the test to be ignored.

The equivalent code using `#[test]` does not cause a test failure.

```rust
#[test]
#[ignore]
fn fail() {
    panic!();
}
```

Cargo output:

```shell
$ cargo test
[...]
running 1 test
test fail ... ignored
```

---
## Context

I was trying to run [`proptest`](https://crates.io/crates/proptest) tests under assay. Since they take a few seconds to run each, I was trying to ignore them, which is how I discovered the problem.

**Comment by korrat** [comment]
That sounds good. If you'd like, I can also try my hand on that and open a PR on the weekend.

**Comment by mgattozzi** [comment]
@korrat If you want to contribute feel free! There's no pressure to do so though 😄
