### ISSUE TITLE
Use `bifurcate` instead of `rusty-fork`

### ISSUE THREAD

**Issue by mgattozzi** [mgattozzi/assay#3]
`rusty-fork` was great to get `assay` working but it has a few problems:

- It's not maintained
- It can't handle `?`
- Inter process communication isn't the greatest
- Handling failures could be better

I've decided to make a crate [`bifurcate`](https://github.com/mgattozzi/bifurcate) that does this from the ground up.

**Comment by estk** [comment]
bifurcate is not public, I would be very interested in a rusty fork alternative
