### ISSUE TITLE
Import pretty_assertions_sorted as well as pretty_assertions

### ISSUE THREAD

**Issue by gibfahn** [mgattozzi/assay#4]
See https://github.com/colin-kiegel/rust-pretty-assertions/issues/85

Needing to assert on the results of HashMaps / HashSets is something I've needed to do quite often, so proposing this for inclusion in the crate.

This crate provides `assert_eq_sorted!()`, so won't conflict with the default `pretty_assertions` crate's override.

**Comment by mgattozzi** [comment]
Oh I would absolutely love this! If you want to implement it or someone else here's what needs to be done:

1. [This line](https://github.com/mgattozzi/assay/blob/aa1082551de5bebd8a84a65640ea0d4859adc6a9/src/lib.rs#L21) would need to change to use the [pretty-assertions-sorted](https://docs.rs/pretty_assertions_sorted/latest/pretty_assertions_sorted/) crate and add the `assert_eq_sorted` macro to the use statement.
2. [This line](https://github.com/mgattozzi/assay/blob/aa1082551de5bebd8a84a65640ea0d4859adc6a9/Cargo.toml#L16) in the `Cargo.toml` being updated to that crate as well 
3. [This line](https://github.com/mgattozzi/assay/blob/aa1082551de5bebd8a84a65640ea0d4859adc6a9/assay-proc-macro/src/lib.rs#L191) would need to also be updated to include the `assert_eq_sorted` macro as well!
4. Update the readme/docs with the new macro
5. Bonus step, but not a major requirement for approval: Include an example either in the docs or examples for using it!

The changes are relatively small and I'm happy to accept a PR or get around to it when I have time!

**Comment by mgattozzi** [comment]
I also promoted this on [my twitter account](https://twitter.com/mgattozzi/status/1496224723491078147?s=20&t=0ENr69l6sX27Hd0C4R_cQg) in case someone wants to claim it and you do not have the time! Whoever wants to do it just claim it in a comment below and open up a PR and if you started but haven't necessarily finished opening up a draft PR is also fine!

**Comment by msfjarvis** [comment]
I'd like to take this up

**Comment by LuisCardosoOliveira** [comment]
Hey! I'd love to take it if possible 😄

**Comment by LuisCardosoOliveira** [comment]
Hey 😃 I’d love to take it

**Comment by mgattozzi** [comment]
@gibfahn this has now been added thanks to @msfjarvis! I'm happy to push a point release if you need this feature soon.

**Comment by gibfahn** [comment]
Thanks @mgattozzi ! I'm not doing so well at GitHub notifications 😅 . I'm happy to pull in a git dependency until the next version.

**Comment by mgattozzi** [comment]
Whomst among us really can stay on top of all of our notifications? Cool. It might be a bit till then, but if you do want to switch off that as a dep let me know.
