### ISSUE TITLE
Make tokio an optional dependency (+ maybe enabled by default)?

### ISSUE THREAD

**Issue by sunshowers** [mgattozzi/assay#8]
What do you think of making tokio an optional dependency, enabled by default? I'd love to use assay for some tests that have nothing to do with tokio :)

**Comment by mgattozzi** [comment]
@sunshowers I think that would be great as I know people don't always want things. I think I'd like a feature flag then to be called `tokio` that's enabled by default and can be turned off with `no-default-features`. In the future I'd like to let people choose their executor as well so this is a step in the right direction there!

**Comment by mgattozzi** [comment]
@sunshowers I've implemented this now. I'll want to do a thing or two more before cutting another release, but wanted to let you know you can depend on this now via git in the meantime 😄
